version: '3'
services:
  telecom-app:
    image: telecom
    environment:
        JAVA_OPTIONS: -Xmx512m -Xms256m
        SPRING_PROFILES_ACTIVE: dev
        APP_START_SLEEP: 5 # gives time for other services to boot before the application
        POSTGRES_USER: ${POSTGRES_USER:-merit_money}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-merit}
        POSTGRES_PRIMARY_USER: postgres
        POSTGRES_PRIMARY_PASSWORD: yoursecurepassword
        POSTGRES_DB: ${POSTGRES_DB:-merit-money-dev}
        TZ: GMT
    ports:
      - 8081:8081
    volumes:
      - ./logs/externalLogs/:/logs
